spring.application.name = api-gateway

server.port = 8010

eureka.client.service-url.default-zone = http://localhost:8761

eureka.client.gateway.discovery.locator.enabled = true
eureka.client.gateway.discovery.locator.lower-case-service-id = true

eureka.instance.hostname = localhost
eureka.instance.instance-id = ${spring.application.name}:${server.port}
eureka.instance.prefer-ip-address=true

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update